# Normal Test Cases
model:
  _target_: torch.nn.Linear
  _convert_: none
  in_features: 784
  out_features: 10

optimizer:
  _target_: torch.optim.Adam
  _recursive_: true
  _partial_: true
  lr: 0.001

hydra:
  _target_: hydra.utils.get_method
  path: torch.nn.functional.relu

# Nested references.
nested:
  value1: 100
  value2: ${.value1}
  deep:
    value3: ${..value1}
    value4: ${.value3}
